# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.6
          cache: true

      - name: Build bundle
        run: |

          CC=mips-linux-gcc GOOS=linux GOARCH=mipsle CGO_ENABLED=0 GOMIPS=softfloat go build -v -ldflags="-w -s" -o ./dist/linux-mipsle-softfloat/caddy ./cmd/caddy/main.go
          cd ./dist/linux-mipsle-softfloat/
          tar  zcvf ../../dist/caddy-linux-mipsle-softfloat.tgz ./*
          cd ../../
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/master')
        with:
          tag_name: Continuous-integration-${{ github.sha }}
          #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            dist/*.tgz
